### ISSUE TITLE
Go-Around Alarm

### ISSUE THREAD

**Issue by kye-taylor** [VATSIM-UK/uk-controller-plugin#128]
**Some audible sound when a go-around occurs**

Two ways I can think about achieving this:

1. Preset criteria that identify true go-arounds, and doesn't mistake anything else (i.e VFR CTS)
From this, it will auto alarm with no interaction.

or

2. Toggle button that the  _TWR can press in the event of a go-around (Similar to what happens  real world, as they mark it on the strip)

Obviously this would need to be an option to turn on and off in the OP menu,  Could house the volume slider within as well?

This must:
- Only used by a _TWR controller
- Only be used with true Go-Around's
- Have an on and off button within the OF (+Maybe a volume slider?)
- Been a quick access button that won't be accidentally pressed  (In our homemade altitude list?)

**Comment by kye-taylor** [comment]
Can you add Enhancement Please

**Comment by louielister** [comment]
As an APP controller it would be good to know ASAP when there is a go around, especially in events. I'd argue we shouldn't restrict it to TWR controllers only and have it as an optional setting that anyone can turn on if they want it on. 

Maybe a something where you can add an aircraft to 'a list' that allows you to purposely ignore 'go arounds' for certain aircraft? i.e somebody in the IFR circuit.

**Comment by LEWISC44** [comment]
Any update on this?

**Comment by hsugden** [comment]
Thoughts regarding being able to trigger this...
- controller must be on TWR (with a primary frequency set)
- to trigger on another controller's setup, APP needs to be covered by either APP or CTR top-down
- only alarms for IFR aircraft would be beamed to other controller's instances
- VFR go arounds would play on the controller's own instance only
- 60-second global timeout for each airport (except EGLL, since parallel runways) 
- several minute timeout for the same callsign
- maybe also the tag must be unassumed and < 2500ft?

**Comment by AndyTWF** [comment]
Hi @kye-taylor @LEWISC44  - this has been implemented as of UKCP 3.8.0.
