### ISSUE TITLE
D1 intention code not displaying

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#207]
I use an up to date airways.txt file in EuroScope, but have noticed a good number of flights in recent weeks displaying the destination airport as intention code when routing via KONAN, instead of **D1**. What seems to be common about these flight plans is that the fix at the end of the UL607 they have filed is no longer on the UL607 - this is my best guess based on a few of them. I'm just a little concerned that these flights - even if planned slightly incorrectly - could do with a less intrusive intention code as opposed to their 4-letter ICAO destination, especially since there is little we can do with pilots' AIRAC data/flight plans not aligning with the latest AIRAC cycle.

I _think_ the intention code **D** is for aircraft via KOK, as much as D1 is. I am proposing we - potentially as a "VATSIMism" - display an intention code **D** for aircraft via _KONAN_ who do **not** meet the conditions of EB/D1, to 'catch' these wayward soles... any thoughts?

![image](https://user-images.githubusercontent.com/12017284/104128749-35887300-5361-11eb-8972-cdf1208d8b91.png)

**Comment by AndyTWF** [comment]
Hi @hsugden - the way UKCP is currently written, adding KONAN would mean it would override all the other routes. This particular issue is probably happening because the exit point doesn't think they're exiting there (their onward direction of travel is what we use to determine if they're entering or leaving the FIR).

My proposal would be that we update the KOK exit points to allow a wider range of directions post-KOK, which would fix it. Can you send me a route string from one of the affected flights so I can have a look at it?

**Comment by hsugden** [comment]
Would it be possible to check for “KONAN UL607” in the route string? This would probably catch the problem a/c.

**Comment by AndyTWF** [comment]
Possibly, yes - I'll have a look!

**Comment by AndyTWF** [comment]
Hi @hsugden - I've done a fix that will make traffic via KONAN display "D1" via Koksy, or just "D" otherwise.

**Comment by hsugden** [comment]
Great, thank you!
